version: '3.8'

services:
    restest_server:
      image: ghcr.io/ndw/3.0-test-suite/xproctest:0.9.0
      container_name: restest
      ports:
        - 8222:80
      working_dir: /src
      volumes:
        - ./apache2/htdocs:/usr/local/apache2/htdocs:z
        - ./apache2/cache:/usr/local/apache2/cache:z
        - ./apache2/cgi-bin:/usr/local/apache2/cgi-bin:z
        - ./apache2/service:/usr/local/apache2/service:z
        - ./apache2/conf:/usr/local/apache2/conf:z,ro
      stdin_open: true
      tty: true
      networks:
        - external_restest_net

networks:
  external_restest_net: {}
